name: Retrain Model CI

on:
  push:
    branches:
      - main
    paths:
      - "MLProject/**"

jobs:
  train-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12.7

      - name: Install MLflow
        shell: bash -l {0}
        run: pip install mlflow

      - name: Run MLflow Project to Train Model
        shell: bash -l {0}
        run: mlflow run ./MLProject

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifact
          path: MLProject/model.pkl
